// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:lista_compras/models/categoria_item.dart';
import 'package:lista_compras/models/item.dart';
import 'package:lista_compras/models/lista_compras.dart';
import 'package:lista_compras/models/preco_historico.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoriaItemAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ListaComprasAdapter());
    registerAdapter(PrecoEntradaAdapter());
    registerAdapter(PrecoHistoricoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoriaItemAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ListaComprasAdapter());
    registerAdapter(PrecoEntradaAdapter());
    registerAdapter(PrecoHistoricoAdapter());
  }
}
